/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.57
 * Generated at: 2026-09-09 01:22:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.*;
import jakarta.servlet.ServletRegistration;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("jakarta.servlet.ServletRegistration");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"ko\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>myapp - 빌드된 서블릿 & JSP 목록</title>\n");
      out.write("    <style>\n");
      out.write("        * {\n");
      out.write("            box-sizing: border-box;\n");
      out.write("            margin: 0;\n");
      out.write("            padding: 0;\n");
      out.write("            font-family: 'Segoe UI', -apple-system, BlinkMacSystemFont, Roboto, 'Malgun Gothic', sans-serif;\n");
      out.write("        }\n");
      out.write("        body {\n");
      out.write("            background-color: #f0f2f5;\n");
      out.write("            color: #1c1e21;\n");
      out.write("            padding: 40px 20px;\n");
      out.write("        }\n");
      out.write("        .container {\n");
      out.write("            max-width: 800px;\n");
      out.write("            margin: 0 auto;\n");
      out.write("            background: #ffffff;\n");
      out.write("            border-radius: 12px;\n");
      out.write("            box-shadow: 0 4px 16px rgba(0, 0, 0, 0.08);\n");
      out.write("            padding: 30px;\n");
      out.write("        }\n");
      out.write("        h1 {\n");
      out.write("            font-size: 22px;\n");
      out.write("            font-weight: 700;\n");
      out.write("            color: #0f172a;\n");
      out.write("            margin-bottom: 6px;\n");
      out.write("            display: flex;\n");
      out.write("            align-items: center;\n");
      out.write("            gap: 8px;\n");
      out.write("        }\n");
      out.write("        .desc {\n");
      out.write("            color: #64748b;\n");
      out.write("            font-size: 14px;\n");
      out.write("            margin-bottom: 24px;\n");
      out.write("        }\n");
      out.write("        .section-header {\n");
      out.write("            font-size: 15px;\n");
      out.write("            font-weight: 700;\n");
      out.write("            color: #334155;\n");
      out.write("            margin: 24px 0 12px 0;\n");
      out.write("            padding-bottom: 8px;\n");
      out.write("            border-bottom: 2px solid #e2e8f0;\n");
      out.write("            display: flex;\n");
      out.write("            align-items: center;\n");
      out.write("            justify-content: space-between;\n");
      out.write("        }\n");
      out.write("        .badge {\n");
      out.write("            font-size: 12px;\n");
      out.write("            font-weight: 600;\n");
      out.write("            padding: 3px 8px;\n");
      out.write("            border-radius: 9999px;\n");
      out.write("        }\n");
      out.write("        .badge-servlet {\n");
      out.write("            background-color: #ffedd5;\n");
      out.write("            color: #c2410c;\n");
      out.write("        }\n");
      out.write("        .badge-jsp {\n");
      out.write("            background-color: #dcfce7;\n");
      out.write("            color: #15803d;\n");
      out.write("        }\n");
      out.write("        .list {\n");
      out.write("            list-style: none;\n");
      out.write("            display: flex;\n");
      out.write("            flex-direction: column;\n");
      out.write("            gap: 10px;\n");
      out.write("        }\n");
      out.write("        .item {\n");
      out.write("            border: 1px solid #e2e8f0;\n");
      out.write("            border-radius: 8px;\n");
      out.write("            padding: 14px 18px;\n");
      out.write("            display: flex;\n");
      out.write("            align-items: center;\n");
      out.write("            justify-content: space-between;\n");
      out.write("            background: #fafafa;\n");
      out.write("            transition: all 0.2s;\n");
      out.write("        }\n");
      out.write("        .item:hover {\n");
      out.write("            border-color: #3b82f6;\n");
      out.write("            background: #f0f7ff;\n");
      out.write("            transform: translateY(-1px);\n");
      out.write("        }\n");
      out.write("        .item-info {\n");
      out.write("            display: flex;\n");
      out.write("            flex-direction: column;\n");
      out.write("            gap: 3px;\n");
      out.write("        }\n");
      out.write("        .item-title {\n");
      out.write("            font-size: 15px;\n");
      out.write("            font-weight: 600;\n");
      out.write("            color: #1e293b;\n");
      out.write("        }\n");
      out.write("        .item-path {\n");
      out.write("            font-size: 13px;\n");
      out.write("            color: #64748b;\n");
      out.write("            font-family: 'Consolas', monospace;\n");
      out.write("        }\n");
      out.write("        .btn-run {\n");
      out.write("            display: inline-flex;\n");
      out.write("            align-items: center;\n");
      out.write("            gap: 4px;\n");
      out.write("            background-color: #2563eb;\n");
      out.write("            color: #ffffff;\n");
      out.write("            text-decoration: none;\n");
      out.write("            font-size: 13px;\n");
      out.write("            font-weight: 600;\n");
      out.write("            padding: 8px 16px;\n");
      out.write("            border-radius: 6px;\n");
      out.write("            transition: background 0.2s;\n");
      out.write("        }\n");
      out.write("        .btn-run:hover {\n");
      out.write("            background-color: #1d4ed8;\n");
      out.write("        }\n");
      out.write("        .empty-msg {\n");
      out.write("            padding: 16px;\n");
      out.write("            text-align: center;\n");
      out.write("            color: #94a3b8;\n");
      out.write("            font-size: 14px;\n");
      out.write("            background: #f8fafc;\n");
      out.write("            border-radius: 8px;\n");
      out.write("        }\n");
      out.write("        .footer {\n");
      out.write("            margin-top: 30px;\n");
      out.write("            padding-top: 16px;\n");
      out.write("            border-top: 1px solid #f1f5f9;\n");
      out.write("            text-align: center;\n");
      out.write("            font-size: 12px;\n");
      out.write("            color: #94a3b8;\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<div class=\"container\">\n");
      out.write("    <h1>myapp 빌드 목록 (서블릿 & JSP)</h1>\n");
      out.write("    <p class=\"desc\">프로젝트에 빌드/등록된 서블릿 및 JSP 파일 목록입니다. [실행] 버튼을 누르면 해당 페이지로 바로 이동합니다.</p>\n");
      out.write("\n");
      out.write("    <!-- 1. 등록된 서블릿 목록 -->\n");
      out.write("    <div class=\"section-header\">\n");
      out.write("        <span>등록된 서블릿 (Servlets)</span>\n");
      out.write("        <span class=\"badge badge-servlet\">Servlet</span>\n");
      out.write("    </div>\n");
      out.write("    <ul class=\"list\">\n");
      out.write("        ");

            Map<String, ? extends ServletRegistration> servletMap = application.getServletRegistrations();
            int servletCount = 0;
            if (servletMap != null) {
                for (Map.Entry<String, ? extends ServletRegistration> entry : servletMap.entrySet()) {
                    String name = entry.getKey();
                    ServletRegistration reg = entry.getValue();
                    String className = reg.getClassName();
                    
                    // 톰캣 기본 내장 서블릿(default, jsp) 제외
                    if ("default".equals(name) || "jsp".equals(name) || (className != null && className.startsWith("org.apache.catalina"))) {
                        continue;
                    }
                    
                    Collection<String> mappings = reg.getMappings();
                    if (mappings != null && !mappings.isEmpty()) {
                        for (String mapping : mappings) {
                            servletCount++;
                            String url = request.getContextPath() + (mapping.startsWith("/") ? mapping : "/" + mapping);
        
      out.write("\n");
      out.write("            <li class=\"item\">\n");
      out.write("                <div class=\"item-info\">\n");
      out.write("                    <span class=\"item-title\">");
      out.print( (className != null && !className.isEmpty()) ? className : name );
      out.write("</span>\n");
      out.write("                    <span class=\"item-path\">URL: ");
      out.print( mapping );
      out.write("</span>\n");
      out.write("                </div>\n");
      out.write("                <a href=\"");
      out.print( url );
      out.write("\" class=\"btn-run\" target=\"_blank\">실행 ▶</a>\n");
      out.write("            </li>\n");
      out.write("        ");

                        }
                    }
                }
            }
            if (servletCount == 0) {
        
      out.write("\n");
      out.write("            <li class=\"empty-msg\">등록된 사용자 서블릿이 없습니다.</li>\n");
      out.write("        ");

            }
        
      out.write("\n");
      out.write("    </ul>\n");
      out.write("\n");
      out.write("    <!-- 2. JSP 및 HTML 목록 -->\n");
      out.write("    <div class=\"section-header\">\n");
      out.write("        <span>JSP 및 웹 페이지 (JSP / HTML)</span>\n");
      out.write("        <span class=\"badge badge-jsp\">JSP</span>\n");
      out.write("    </div>\n");
      out.write("    <ul class=\"list\">\n");
      out.write("        ");

            int jspCount = 0;
            
            // 재귀적으로 JSP 파일 탐색 람다/헬퍼
            class ResourceHelper {
                void scan(ServletContext ctx, String path, List<String> resultList) {
                    Set<String> paths = ctx.getResourcePaths(path);
                    if (paths == null) return;
                    for (String p : paths) {
                        if (p.startsWith("/WEB-INF") || p.startsWith("/META-INF") || p.equals("/index.jsp")) {
                            continue;
                        }
                        if (p.endsWith("/")) {
                            scan(ctx, p, resultList);
                        } else if (p.endsWith(".jsp") || p.endsWith(".html") || p.endsWith(".htm")) {
                            resultList.add(p);
                        }
                    }
                }
            }
            
            List<String> jspList = new ArrayList<>();
            new ResourceHelper().scan(application, "/", jspList);
            Collections.sort(jspList);
            
            for (String jspPath : jspList) {
                jspCount++;
                String url = request.getContextPath() + (jspPath.startsWith("/") ? jspPath : "/" + jspPath);
        
      out.write("\n");
      out.write("            <li class=\"item\">\n");
      out.write("                <div class=\"item-info\">\n");
      out.write("                    <span class=\"item-title\">");
      out.print( jspPath.substring(jspPath.lastIndexOf('/') + 1) );
      out.write("</span>\n");
      out.write("                    <span class=\"item-path\">");
      out.print( jspPath );
      out.write("</span>\n");
      out.write("                </div>\n");
      out.write("                <a href=\"");
      out.print( url );
      out.write("\" class=\"btn-run\" target=\"_blank\">실행 ▶</a>\n");
      out.write("            </li>\n");
      out.write("        ");

            }
            if (jspCount == 0) {
        
      out.write("\n");
      out.write("            <li class=\"empty-msg\">배포된 JSP 파일이 없습니다.</li>\n");
      out.write("        ");

            }
        
      out.write("\n");
      out.write("    </ul>\n");
      out.write("\n");
      out.write("    <div class=\"footer\">\n");
      out.write("        Tomcat Context: <strong>");
      out.print( request.getContextPath() );
      out.write("</strong> | 총 서블릿 ");
      out.print( servletCount );
      out.write("개, JSP ");
      out.print( jspCount );
      out.write("개 감지됨\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
