/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.57
 * Generated at: 2026-09-11 01:33:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.ch09;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import ch09.TeamBean;
import java.util.Vector;

public final class teamList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.LinkedHashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/ch09/themeHead.jsp", Long.valueOf(1789089811142L));
    _jspx_dependants.put("/ch09/themeToggle.jsp", Long.valueOf(1789090254388L));
    _jspx_dependants.put("/common/theme.jsp", Long.valueOf(1789090242827L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("ch09.TeamBean");
    _jspx_imports_classes.add("java.util.Vector");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!-- teamList.jsp -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      ch09.TeamMgr mgr = null;
      mgr = (ch09.TeamMgr) _jspx_page_context.getAttribute("mgr", jakarta.servlet.jsp.PageContext.PAGE_SCOPE);
      if (mgr == null){
        mgr = new ch09.TeamMgr();
        _jspx_page_context.setAttribute("mgr", mgr, jakarta.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write('\r');
      out.write('\n');
 Vector<TeamBean> vlist = mgr.listTeam();
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>Team Mgr</title>\r\n");
      out.write("<script>\r\n");
      out.write("	(function () {\r\n");
      out.write("		try {\r\n");
      out.write("			if (localStorage.getItem(\"theme\") === \"dark\") {\r\n");
      out.write("				document.documentElement.classList.add(\"dark\");\r\n");
      out.write("			}\r\n");
      out.write("		} catch (e) {}\r\n");
      out.write("	})();\r\n");
      out.write("</script>\r\n");
      out.write("<script>\r\n");
      out.write("	tailwind.config = { darkMode: \"class\" };\r\n");
      out.write("</script>\r\n");
      out.write("<script src=\"https://cdn.tailwindcss.com\"></script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"min-h-screen bg-gradient-to-br from-slate-50 via-indigo-50 to-slate-100 text-slate-800 dark:from-slate-950 dark:via-slate-900 dark:to-indigo-950 dark:text-slate-100\">\r\n");
      out.write("<div class=\"mx-auto max-w-4xl px-4 py-12\">\r\n");
      out.write("	<header class=\"mb-8 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between\">\r\n");
      out.write("		<div>\r\n");
      out.write("			<p class=\"text-sm font-medium tracking-wide text-indigo-600 dark:text-indigo-400\">Chapter 09</p>\r\n");
      out.write("			<h1 class=\"mt-1 text-3xl font-bold tracking-tight text-slate-900 dark:text-white\">Team List</h1>\r\n");
      out.write("			<p class=\"mt-1 text-sm text-slate-500 dark:text-slate-400\">등록된 팀원 ");
      out.print(vlist.size());
      out.write("명</p>\r\n");
      out.write("		</div>\r\n");
      out.write("		<a href=\"teamInsert.jsp\"\r\n");
      out.write("			class=\"inline-flex items-center justify-center rounded-lg bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white shadow-sm transition hover:bg-indigo-700\">\r\n");
      out.write("			팀원 등록\r\n");
      out.write("		</a>\r\n");
      out.write("	</header>\r\n");
      out.write("\r\n");
      out.write("	<div class=\"overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm dark:border-slate-700 dark:bg-slate-800\">\r\n");
      out.write("		<table class=\"min-w-full divide-y divide-slate-200 text-sm dark:divide-slate-700\">\r\n");
      out.write("			<thead class=\"bg-slate-800 text-left text-xs font-semibold uppercase tracking-wider text-slate-100 dark:bg-slate-950\">\r\n");
      out.write("				<tr>\r\n");
      out.write("					<th class=\"px-4 py-3\">번호</th>\r\n");
      out.write("					<th class=\"px-4 py-3\">이름</th>\r\n");
      out.write("					<th class=\"px-4 py-3\">사는곳</th>\r\n");
      out.write("					<th class=\"px-4 py-3\">나이</th>\r\n");
      out.write("					<th class=\"px-4 py-3\">팀명</th>\r\n");
      out.write("					<th class=\"px-4 py-3 text-center\">상세</th>\r\n");
      out.write("				</tr>\r\n");
      out.write("			</thead>\r\n");
      out.write("			<tbody class=\"divide-y divide-slate-100 dark:divide-slate-700\">\r\n");
      out.write("			");

				if (vlist.isEmpty()) {
			
      out.write("\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td colspan=\"6\" class=\"px-4 py-12 text-center text-slate-400\">등록된 팀원이 없습니다.</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("			");

				}
				for(int i = 0; i < vlist.size(); i++) {
					TeamBean bean = vlist.get(i);
					int num = bean.getNum();
			
      out.write("\r\n");
      out.write("				<tr class=\"transition hover:bg-indigo-50/60 dark:hover:bg-slate-700/60\">\r\n");
      out.write("					<td class=\"px-4 py-3\">\r\n");
      out.write("						<a href=\"teamRead.jsp?num=");
      out.print(num);
      out.write("\" class=\"font-medium text-indigo-600 hover:text-indigo-800 dark:text-indigo-400 dark:hover:text-indigo-300\">");
      out.print(i+1);
      out.write("</a>\r\n");
      out.write("					</td>\r\n");
      out.write("					<td class=\"px-4 py-3 font-medium text-slate-900 dark:text-slate-100\">");
      out.print(bean.getName());
      out.write("</td>\r\n");
      out.write("					<td class=\"px-4 py-3 text-slate-600 dark:text-slate-300\">");
      out.print(bean.getCity());
      out.write("</td>\r\n");
      out.write("					<td class=\"px-4 py-3 text-slate-600 dark:text-slate-300\">");
      out.print(bean.getAge());
      out.write("</td>\r\n");
      out.write("					<td class=\"px-4 py-3\">\r\n");
      out.write("						<span class=\"inline-flex rounded-full bg-indigo-100 px-2.5 py-0.5 text-xs font-medium text-indigo-700 dark:bg-indigo-900/60 dark:text-indigo-200\">");
      out.print(bean.getTeam());
      out.write("</span>\r\n");
      out.write("					</td>\r\n");
      out.write("					<td class=\"px-4 py-3 text-center\">\r\n");
      out.write("						<button type=\"button\" onclick=\"location.href='teamRead.jsp?num=");
      out.print(num);
      out.write("'\"\r\n");
      out.write("							class=\"rounded-md border border-slate-200 bg-white px-3 py-1.5 text-xs font-medium text-slate-700 shadow-sm transition hover:border-indigo-300 hover:text-indigo-700 dark:border-slate-600 dark:bg-slate-700 dark:text-slate-200 dark:hover:border-indigo-400 dark:hover:text-indigo-300\">\r\n");
      out.write("							상세\r\n");
      out.write("						</button>\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("			");
}
      out.write("\r\n");
      out.write("			</tbody>\r\n");
      out.write("		</table>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");
      out.write('\n');
      out.write("\n");
      out.write("<!-- ======================================================== -->\n");
      out.write("<!-- Global Theme Component (Dark / Light Mode Toggle)         -->\n");
      out.write("<!-- ======================================================== -->\n");
      out.write("<script>\n");
      out.write("	(function () {\n");
      out.write("		try {\n");
      out.write("			var savedTheme = localStorage.getItem(\"theme\") || \"light\";\n");
      out.write("			if (savedTheme === \"dark\") {\n");
      out.write("				document.documentElement.classList.add(\"dark\");\n");
      out.write("			} else {\n");
      out.write("				document.documentElement.classList.remove(\"dark\");\n");
      out.write("			}\n");
      out.write("		} catch (e) {}\n");
      out.write("	})();\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("<style id=\"global-theme-styles\">\n");
      out.write("	/* 1. 기본 화면 전환 애니메이션 */\n");
      out.write("	html {\n");
      out.write("		transition: background-color 0.25s ease, color 0.25s ease;\n");
      out.write("	}\n");
      out.write("\n");
      out.write("	/* 2. 일반 JSP / HTML 페이지를 위한 범용 다크모드 스타일 */\n");
      out.write("	html.dark {\n");
      out.write("		color-scheme: dark;\n");
      out.write("	}\n");
      out.write("\n");
      out.write("	html.dark body:not([class*=\"dark:\"]) {\n");
      out.write("		background-color: #0f172a !important;\n");
      out.write("		color: #f1f5f9 !important;\n");
      out.write("	}\n");
      out.write("\n");
      out.write("	/* 컨테이너, 카드, 박스류 */\n");
      out.write("	html.dark .container,\n");
      out.write("	html.dark .card,\n");
      out.write("	html.dark fieldset {\n");
      out.write("		background-color: #1e293b !important;\n");
      out.write("		color: #f1f5f9 !important;\n");
      out.write("		border-color: #334155 !important;\n");
      out.write("	}\n");
      out.write("\n");
      out.write("	/* 텍스트 및 제목 */\n");
      out.write("	html.dark h1:not([class*=\"dark:\"]),\n");
      out.write("	html.dark h2:not([class*=\"dark:\"]),\n");
      out.write("	html.dark h3:not([class*=\"dark:\"]),\n");
      out.write("	html.dark h4:not([class*=\"dark:\"]) {\n");
      out.write("		color: #f8fafc !important;\n");
      out.write("	}\n");
      out.write("\n");
      out.write("	/* 일반 HTML 테이블 (구구단 등) */\n");
      out.write("	html.dark table:not([class*=\"divide-\"]):not([class*=\"dark:\"]) {\n");
      out.write("		border-color: #334155 !important;\n");
      out.write("	}\n");
      out.write("	html.dark table:not([class*=\"divide-\"]) caption {\n");
      out.write("		color: #f8fafc !important;\n");
      out.write("	}\n");
      out.write("	html.dark table:not([class*=\"divide-\"]) th:not([class*=\"dark:\"]) {\n");
      out.write("		background-color: #334155 !important;\n");
      out.write("		color: #f8fafc !important;\n");
      out.write("		border-color: #475569 !important;\n");
      out.write("	}\n");
      out.write("	html.dark table:not([class*=\"divide-\"]) td:not([class*=\"dark:\"]) {\n");
      out.write("		background-color: #1e293b !important;\n");
      out.write("		color: #cbd5e1 !important;\n");
      out.write("		border-color: #334155 !important;\n");
      out.write("	}\n");
      out.write("	html.dark table:not([class*=\"divide-\"]) tr:hover td:not([class*=\"dark:\"]) {\n");
      out.write("		background-color: #2c3e55 !important;\n");
      out.write("	}\n");
      out.write("\n");
      out.write("	/* 폼 입력창 */\n");
      out.write("	html.dark input[type=\"text\"],\n");
      out.write("	html.dark input[type=\"password\"],\n");
      out.write("	html.dark input[type=\"number\"],\n");
      out.write("	html.dark input[type=\"email\"],\n");
      out.write("	html.dark input[type=\"search\"],\n");
      out.write("	html.dark select,\n");
      out.write("	html.dark textarea {\n");
      out.write("		background-color: #1e293b !important;\n");
      out.write("		color: #f8fafc !important;\n");
      out.write("		border: 1px solid #475569 !important;\n");
      out.write("	}\n");
      out.write("	html.dark input::placeholder,\n");
      out.write("	html.dark textarea::placeholder {\n");
      out.write("		color: #64748b !important;\n");
      out.write("	}\n");
      out.write("\n");
      out.write("	/* index.jsp 대시보드 전용 다크모드 대응 */\n");
      out.write("	html.dark .item {\n");
      out.write("		background: #1e293b !important;\n");
      out.write("		border-color: #334155 !important;\n");
      out.write("	}\n");
      out.write("	html.dark .item:hover {\n");
      out.write("		background: #24344d !important;\n");
      out.write("		border-color: #3b82f6 !important;\n");
      out.write("	}\n");
      out.write("	html.dark .item-title {\n");
      out.write("		color: #f8fafc !important;\n");
      out.write("	}\n");
      out.write("	html.dark .item-path {\n");
      out.write("		color: #94a3b8 !important;\n");
      out.write("	}\n");
      out.write("	html.dark .section-header {\n");
      out.write("		color: #cbd5e1 !important;\n");
      out.write("		border-bottom-color: #334155 !important;\n");
      out.write("	}\n");
      out.write("	html.dark .desc {\n");
      out.write("		color: #94a3b8 !important;\n");
      out.write("	}\n");
      out.write("	html.dark .empty-msg {\n");
      out.write("		background: #1e293b !important;\n");
      out.write("		color: #94a3b8 !important;\n");
      out.write("	}\n");
      out.write("	html.dark .footer {\n");
      out.write("		border-top-color: #334155 !important;\n");
      out.write("		color: #64748b !important;\n");
      out.write("	}\n");
      out.write("\n");
      out.write("	/* 일반 링크 색상 보정 */\n");
      out.write("	html.dark a:not([class*=\"btn-\"]):not([class*=\"bg-\"]):not([class*=\"text-\"]) {\n");
      out.write("		color: #60a5fa !important;\n");
      out.write("	}\n");
      out.write("\n");
      out.write("	/* ======================================================== */\n");
      out.write("	/* 우측 하단 플로팅 테마 전환 위젯 스타일                   */\n");
      out.write("	/* ======================================================== */\n");
      out.write("	#global-theme-widget {\n");
      out.write("		position: fixed;\n");
      out.write("		bottom: 20px;\n");
      out.write("		right: 20px;\n");
      out.write("		z-index: 999999;\n");
      out.write("		display: inline-flex;\n");
      out.write("		align-items: center;\n");
      out.write("		background: rgba(255, 255, 255, 0.88);\n");
      out.write("		border: 1px solid rgba(203, 213, 225, 0.85);\n");
      out.write("		border-radius: 9999px;\n");
      out.write("		padding: 3px;\n");
      out.write("		box-shadow: 0 4px 16px rgba(0, 0, 0, 0.12), 0 2px 4px rgba(0, 0, 0, 0.05);\n");
      out.write("		backdrop-filter: blur(10px);\n");
      out.write("		-webkit-backdrop-filter: blur(10px);\n");
      out.write("		user-select: none;\n");
      out.write("		font-family: -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Malgun Gothic\", sans-serif;\n");
      out.write("	}\n");
      out.write("\n");
      out.write("	html.dark #global-theme-widget {\n");
      out.write("		background: rgba(30, 41, 59, 0.88);\n");
      out.write("		border-color: rgba(71, 85, 105, 0.85);\n");
      out.write("		box-shadow: 0 4px 20px rgba(0, 0, 0, 0.4), 0 2px 6px rgba(0, 0, 0, 0.25);\n");
      out.write("	}\n");
      out.write("\n");
      out.write("	#global-theme-widget button {\n");
      out.write("		display: inline-flex;\n");
      out.write("		align-items: center;\n");
      out.write("		gap: 6px;\n");
      out.write("		padding: 6px 14px;\n");
      out.write("		border-radius: 9999px;\n");
      out.write("		border: none;\n");
      out.write("		outline: none;\n");
      out.write("		cursor: pointer;\n");
      out.write("		font-size: 12px;\n");
      out.write("		font-weight: 600;\n");
      out.write("		line-height: 1;\n");
      out.write("		color: #64748b;\n");
      out.write("		background: transparent;\n");
      out.write("		transition: all 0.2s cubic-bezier(0.4, 0, 0.2, 1);\n");
      out.write("	}\n");
      out.write("\n");
      out.write("	#global-theme-widget button:hover {\n");
      out.write("		color: #1e293b;\n");
      out.write("		background: rgba(0, 0, 0, 0.05);\n");
      out.write("	}\n");
      out.write("\n");
      out.write("	html.dark #global-theme-widget button {\n");
      out.write("		color: #94a3b8;\n");
      out.write("	}\n");
      out.write("\n");
      out.write("	html.dark #global-theme-widget button:hover {\n");
      out.write("		color: #f1f5f9;\n");
      out.write("		background: rgba(255, 255, 255, 0.1);\n");
      out.write("	}\n");
      out.write("\n");
      out.write("	#global-theme-widget button.active {\n");
      out.write("		background: #4f46e5;\n");
      out.write("		color: #ffffff !important;\n");
      out.write("		box-shadow: 0 2px 8px rgba(79, 70, 229, 0.35);\n");
      out.write("	}\n");
      out.write("\n");
      out.write("	html.dark #global-theme-widget button.active {\n");
      out.write("		background: #6366f1;\n");
      out.write("		color: #ffffff !important;\n");
      out.write("		box-shadow: 0 2px 10px rgba(99, 102, 241, 0.5);\n");
      out.write("	}\n");
      out.write("\n");
      out.write("	#global-theme-widget svg {\n");
      out.write("		width: 14px;\n");
      out.write("		height: 14px;\n");
      out.write("		display: inline-block;\n");
      out.write("		vertical-align: middle;\n");
      out.write("	}\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("<div id=\"global-theme-widget\" aria-label=\"테마 설정\">\n");
      out.write("	<button type=\"button\" id=\"theme-light-btn\" onclick=\"setTheme('light')\" title=\"라이트 모드 적용\">\n");
      out.write("		<svg fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" viewBox=\"0 0 24 24\">\n");
      out.write("			<circle cx=\"12\" cy=\"12\" r=\"4\"></circle>\n");
      out.write("			<path d=\"M12 2v2M12 20v2M4.93 4.93l1.41 1.41M17.66 17.66l1.41 1.41M2 12h2M20 12h2M6.34 17.66l-1.41 1.41M19.07 4.93l-1.41 1.41\"></path>\n");
      out.write("		</svg>\n");
      out.write("		<span>Light</span>\n");
      out.write("	</button>\n");
      out.write("	<button type=\"button\" id=\"theme-dark-btn\" onclick=\"setTheme('dark')\" title=\"다크 모드 적용\">\n");
      out.write("		<svg fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" viewBox=\"0 0 24 24\">\n");
      out.write("			<path d=\"M21 12.79A9 9 0 1111.21 3 7 7 0 0021 12.79z\"></path>\n");
      out.write("		</svg>\n");
      out.write("		<span>Dark</span>\n");
      out.write("	</button>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("	function setTheme(theme) {\n");
      out.write("		try {\n");
      out.write("			localStorage.setItem(\"theme\", theme);\n");
      out.write("		} catch (e) {}\n");
      out.write("		if (theme === \"dark\") {\n");
      out.write("			document.documentElement.classList.add(\"dark\");\n");
      out.write("		} else {\n");
      out.write("			document.documentElement.classList.remove(\"dark\");\n");
      out.write("		}\n");
      out.write("		syncThemeButtons();\n");
      out.write("	}\n");
      out.write("\n");
      out.write("	function syncThemeButtons() {\n");
      out.write("		var theme = \"light\";\n");
      out.write("		try {\n");
      out.write("			theme = localStorage.getItem(\"theme\") || \"light\";\n");
      out.write("		} catch (e) {}\n");
      out.write("\n");
      out.write("		var lightBtn = document.getElementById(\"theme-light-btn\");\n");
      out.write("		var darkBtn = document.getElementById(\"theme-dark-btn\");\n");
      out.write("		if (lightBtn && darkBtn) {\n");
      out.write("			if (theme === \"dark\") {\n");
      out.write("				lightBtn.classList.remove(\"active\");\n");
      out.write("				darkBtn.classList.add(\"active\");\n");
      out.write("			} else {\n");
      out.write("				lightBtn.classList.add(\"active\");\n");
      out.write("				darkBtn.classList.remove(\"active\");\n");
      out.write("			}\n");
      out.write("		}\n");
      out.write("	}\n");
      out.write("\n");
      out.write("	syncThemeButtons();\n");
      out.write("</script>\n");
      out.write('\n');
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
