/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.57
 * Generated at: 2026-09-11 01:22:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.ch09;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import ch09.TeamBean;
import ch09.MUtil;

public final class teamUpdate_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("ch09.TeamBean");
    _jspx_imports_classes.add("ch09.MUtil");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!-- teamUpdate.jsp -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      ch09.TeamMgr mgr = null;
      mgr = (ch09.TeamMgr) _jspx_page_context.getAttribute("mgr", jakarta.servlet.jsp.PageContext.PAGE_SCOPE);
      if (mgr == null){
        mgr = new ch09.TeamMgr();
        _jspx_page_context.setAttribute("mgr", mgr, jakarta.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write('\r');
      out.write('\n');

	int num = 0;
	TeamBean bean = null;
	if(request.getParameter("num")==null) {
		// num값이 정상적으로 넘어오지 않을 때
		response.sendRedirect("teamList.jsp");
		return;
	} else if(!MUtil.isNumeric((request.getParameter("num")))) {
		//숫자의 형태의 num이 아닐 때
		response.sendRedirect("teamList.jsp");
		return;
	} else {
		num = MUtil.parseInt(request, "num");
		bean = mgr.getTeam(num);
	}

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>Team Mgr</title>\r\n");
      out.write("<script src=\"https://cdn.tailwindcss.com\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"min-h-screen bg-gradient-to-br from-slate-50 via-indigo-50 to-slate-100 text-slate-800\">\r\n");
      out.write("<div class=\"mx-auto max-w-lg px-4 py-12\">\r\n");
      out.write("	<header class=\"mb-8\">\r\n");
      out.write("		<p class=\"text-sm font-medium tracking-wide text-indigo-600\">Chapter 09</p>\r\n");
      out.write("		<h1 class=\"mt-1 text-3xl font-bold tracking-tight text-slate-900\">Team Update</h1>\r\n");
      out.write("		<p class=\"mt-1 text-sm text-slate-500\">팀원 정보를 수정합니다.</p>\r\n");
      out.write("	</header>\r\n");
      out.write("\r\n");
      out.write("	<form name=\"frm\" method=\"post\" action=\"teamUpdateProc.jsp\"\r\n");
      out.write("		class=\"space-y-5 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm\">\r\n");
      out.write("		<div>\r\n");
      out.write("			<label class=\"mb-1.5 block text-sm font-medium text-slate-700\">번호</label>\r\n");
      out.write("			<input name=\"num\" value=\"");
      out.print(bean.getNum() );
      out.write("\" readonly\r\n");
      out.write("				class=\"w-full cursor-not-allowed rounded-lg border border-slate-200 bg-slate-50 px-3 py-2 text-sm text-slate-500\">\r\n");
      out.write("		</div>\r\n");
      out.write("		<div>\r\n");
      out.write("			<label class=\"mb-1.5 block text-sm font-medium text-slate-700\">이름</label>\r\n");
      out.write("			<input name=\"name\" value=\"");
      out.print(bean.getName() );
      out.write("\"\r\n");
      out.write("				class=\"w-full rounded-lg border border-slate-300 px-3 py-2 text-sm shadow-sm outline-none transition focus:border-indigo-500 focus:ring-2 focus:ring-indigo-200\">\r\n");
      out.write("		</div>\r\n");
      out.write("		<div>\r\n");
      out.write("			<label class=\"mb-1.5 block text-sm font-medium text-slate-700\">사는곳</label>\r\n");
      out.write("			<input name=\"city\" value=\"");
      out.print(bean.getCity() );
      out.write("\"\r\n");
      out.write("				class=\"w-full rounded-lg border border-slate-300 px-3 py-2 text-sm shadow-sm outline-none transition focus:border-indigo-500 focus:ring-2 focus:ring-indigo-200\">\r\n");
      out.write("		</div>\r\n");
      out.write("		<div>\r\n");
      out.write("			<label class=\"mb-1.5 block text-sm font-medium text-slate-700\">나이</label>\r\n");
      out.write("			<input name=\"age\" value=\"");
      out.print(bean.getAge() );
      out.write("\"\r\n");
      out.write("				class=\"w-full rounded-lg border border-slate-300 px-3 py-2 text-sm shadow-sm outline-none transition focus:border-indigo-500 focus:ring-2 focus:ring-indigo-200\">\r\n");
      out.write("		</div>\r\n");
      out.write("		<div>\r\n");
      out.write("			<label class=\"mb-1.5 block text-sm font-medium text-slate-700\">팀명</label>\r\n");
      out.write("			<input name=\"team\" value=\"");
      out.print(bean.getTeam() );
      out.write("\"\r\n");
      out.write("				class=\"w-full rounded-lg border border-slate-300 px-3 py-2 text-sm shadow-sm outline-none transition focus:border-indigo-500 focus:ring-2 focus:ring-indigo-200\">\r\n");
      out.write("		</div>\r\n");
      out.write("		<input type=\"submit\" value=\"UPDATE\"\r\n");
      out.write("			class=\"w-full cursor-pointer rounded-lg bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white shadow-sm transition hover:bg-indigo-700\">\r\n");
      out.write("	</form>\r\n");
      out.write("\r\n");
      out.write("	<p class=\"mt-6\">\r\n");
      out.write("		<a href=\"teamRead.jsp?num=");
      out.print(num);
      out.write("\" class=\"text-sm font-medium text-indigo-600 hover:text-indigo-800\">← READ</a>\r\n");
      out.write("	</p>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
